version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: ecommerce-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_EXPIRATION_MS: ${APP_JWT_EXPIRATION_MS}
      APP_SEED_ADMIN_ENABLED: ${APP_SEED_ADMIN_ENABLED:-false}
      APP_SEED_ADMIN_EMAIL: ${APP_SEED_ADMIN_EMAIL}
      APP_SEED_ADMIN_PASSWORD: ${APP_SEED_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    # Optionally pass extra JVM flags
    # environment:
    #   JAVA_OPTS: -Xms256m -Xmx512m

volumes:
  pgdata:
