server:
  port: 8080

spring:
  application:
    name: ecommerce

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: update   # convenient for local dev/demo
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

  h2:
    console:
      enabled: false
      path: /h2-console

# Swagger / OpenAPI (springdoc)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# CORS defaults and JWT config for local/dev/demo
app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: ${APP_JWT_EXPIRATION_MS}
  cors:
    allowed-origins:
      - "http://localhost:5173"       # React dev server
      - "http://localhost:4200"       # Angular dev server
    allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
  seed:
    admin:
      enabled: ${APP_SEED_ADMIN_ENABLED:false}
      email: ${APP_SEED_ADMIN_EMAIL:}
      password: ${APP_SEED_ADMIN_PASSWORD:}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
